# -*- coding: utf-8 -*-
"""mikołaj_stream.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a7n0KPcmmIDDWsb7OEcWly6IpebhV8um
"""

import streamlit as st
import matplotlib.pyplot as plt
from matplotlib.patches import Circle, Rectangle, Polygon, Ellipse

st.title("🎅 Mikołaj rysowany w Pythonie")

# Ustawienia rysunku
fig, ax = plt.subplots(figsize=(6, 8))
ax.set_aspect("equal")
ax.axis("off")

# --------------------
# KORPUS MIKOŁAJA
# --------------------
body = Rectangle((-1.2, -1.0), 2.4, 2.2, color="red")
ax.add_patch(body)

collar = Rectangle((-1.2, 1.0), 2.4, 0.2, color="white")
ax.add_patch(collar)

belt = Rectangle((-1.2, 0.0), 2.4, 0.2, color="black")
ax.add_patch(belt)

buckle = Rectangle((-0.3, 0.02), 0.6, 0.16, edgecolor="yellow", facecolor="none", linewidth=2)
ax.add_patch(buckle)

for y in [0.7, 0.4, 0.1]:
    button = Circle((0, y), 0.05, color="black")
    ax.add_patch(button)

# Legs & boots
left_leg = Rectangle((-0.7, -1.5), 0.6, 0.5, color="red")
right_leg = Rectangle((0.1, -1.5), 0.6, 0.5, color="red")
ax.add_patch(left_leg)
ax.add_patch(right_leg)

left_boot = Rectangle((-0.8, -1.8), 0.8, 0.3, color="black")
right_boot = Rectangle((0.0, -1.8), 0.8, 0.3, color="black")
ax.add_patch(left_boot)
ax.add_patch(right_boot)

# Arms
left_arm = Rectangle((-1.8, 0.5), 0.6, 1.0, angle=10, color="red")
right_arm = Rectangle((1.2, 0.5), 0.6, 1.0, angle=-10, color="red")
ax.add_patch(left_arm)
ax.add_patch(right_arm)

# Gloves
left_glove = Circle((-1.8, 0.5), 0.25, color="brown")
right_glove = Circle((1.8, 0.5), 0.25, color="brown")
ax.add_patch(left_glove)
ax.add_patch(right_glove)

# Head
head = Circle((0, 1.6), 0.6, color="#ffddb3")
ax.add_patch(head)

beard = Ellipse((0, 1.3), 1.0, 0.9, color="white")
ax.add_patch(beard)

moustache_left = Ellipse((-0.15, 1.45), 0.5, 0.2, angle=15, color="white")
moustache_right = Ellipse((0.15, 1.45), 0.5, 0.2, angle=-15, color="white")
ax.add_patch(moustache_left)
ax.add_patch(moustache_right)

nose = Circle((0, 1.5), 0.08, color="#e0a070")
ax.add_patch(nose)

left_eye = Circle((-0.2, 1.7), 0.06, color="white")
right_eye = Circle((0.2, 1.7), 0.06, color="white")
left_pupil = Circle((-0.2, 1.7), 0.03, color="black")
right_pupil = Circle((0.2, 1.7), 0.03, color="black")
ax.add_patch(left_eye)
ax.add_patch(right_eye)
ax.add_patch(left_pupil)
ax.add_patch(right_pupil)

ax.plot([-0.2, 0, 0.2], [1.32, 1.28, 1.32], color="black", linewidth=2)

# Hat
hat = Polygon([(-0.8, 1.9), (0.8, 1.9), (0, 2.6)], closed=True, color="red")
ax.add_patch(hat)

hat_band = Rectangle((-0.8, 1.8), 1.6, 0.15, color="white")
ax.add_patch(hat_band)

pompom = Circle((0, 2.65), 0.15, color="white")
ax.add_patch(pompom)

# Present
gift_box = Rectangle((1.6, -0.6), 0.6, 0.6, color="green")
gift_ribbon_vertical = Rectangle((1.86, -0.6), 0.08, 0.6, color="yellow")
gift_ribbon_horizontal = Rectangle((1.6, -0.32), 0.6, 0.08, color="yellow")
ax.add_patch(gift_box)
ax.add_patch(gift_ribbon_vertical)
ax.add_patch(gift_ribbon_horizontal)

ax.set_xlim(-2.2, 2.4)
ax.set_ylim(-2.0, 3.0)

# --- WYŚWIETLANIE W STREAMLIT ---
st.pyplot(fig)